services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sourceant
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - sourceant-network
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    env_file:
      - .env

  db:
    image: postgres:13
    container_name: sourceant-db
    environment:
      POSTGRES_DB: sourceant
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - sourceant-network

  redis:
    image: "redis:latest"
    container_name: sourceant-redis
    ports:
      - "6379:6379"
    networks:
      - sourceant-network
    volumes:
      - redis-data:/data

networks:
  sourceant-network:
    driver: bridge

volumes:
  db-data:
  redis-data:
