#!/usr/bin/env python3

import click
import sys
import subprocess
from alembic.config import CommandLine


@click.group()
def cli():
    pass


@click.command(name="db",
               context_settings={"allow_extra_args": True, "ignore_unknown_options": True})
@click.pass_context
def db_command(ctx):
    sys.argv = ["alembic"] + ctx.args
    sys.exit(CommandLine().main())


@click.group(name='code')
def code_group():
    pass


@click.command(name="lint")
def lint_command():
    try:
        # --check flag for linting
        # Ignoring line length violations (E501) handled by black
        subprocess.run(["flake8", ".", "--ignore=E501"], check=True)
        subprocess.run(["black", "--check", "."], check=True)
    except subprocess.CalledProcessError as e:
        print("\nLinting failed! Run 'sourceant code lint:fix' to automatically fix linting issues.")
        sys.exit(e.returncode)


@click.command(name="lint:fix")
def lint_fix_command():
    try:
        subprocess.run(["black", "."], check=True)
        print("Linting issues fixed successfully.")
    except subprocess.CalledProcessError as e:
        print("Error while fixing linting issues:")
        sys.exit(e.returncode)


cli.add_command(db_command)
code_group.add_command(lint_command)
code_group.add_command(lint_fix_command)
cli.add_command(code_group)

if __name__ == "__main__":
    cli()
